<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Application;

class ApplicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $applications = [
            [
                'student_name' => 'Rafael Gomez',
                'course' => 'SITE',
                'year_level' => 'Third Year',
                'age' => '21',
                'id_number' => '21-0606-217',
                'address' => '101 Main St',
                'email' => 'rafael.gomez@example.com',
                'telephone' => '09123456780',
                'picture' => 'rafael.jpg',
                'father_name' => 'Carlos Gomez',
                'father_age' => '50',
                'father_occupation' => 'Driver',
                'mother_name' => 'Lucia Gomez',
                'mother_age' => '48',
                'mother_occupation' => 'Vendor',
                'monthly_income' => '20000',
                'is_literate' => true,
                'tools' => json_encode(['office','design']),
                'can_commit' => true,
                'willing_overtime' => true,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Singing, Drawing',
            ],
            [
                'student_name' => 'Bea Lim',
                'course' => 'SBA',
                'year_level' => 'Second Year',
                'age' => '20',
                'id_number' => '21-0606-218',
                'address' => '202 Second St',
                'email' => 'bea.lim@example.com',
                'telephone' => '09987654322',
                'picture' => 'bea.jpg',
                'father_name' => 'Jose Lim',
                'father_age' => '52',
                'father_occupation' => 'Teacher',
                'mother_name' => 'Ana Lim',
                'mother_age' => '50',
                'mother_occupation' => 'Nurse',
                'monthly_income' => '25000',
                'is_literate' => true,
                'tools' => json_encode(['office','video_conf']),
                'can_commit' => true,
                'willing_overtime' => false,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Dancing, Cooking',
            ],
            [
                'student_name' => 'Miguel Santos',
                'course' => 'SOHS',
                'year_level' => 'Fourth Year',
                'age' => '22',
                'id_number' => '21-0606-219',
                'address' => '303 Third Ave',
                'email' => 'miguel.santos@example.com',
                'telephone' => '09121234568',
                'picture' => 'miguel.jpg',
                'father_name' => 'Roberto Santos',
                'father_age' => '54',
                'father_occupation' => 'Mechanic',
                'mother_name' => 'Luisa Santos',
                'mother_age' => '51',
                'mother_occupation' => 'Housewife',
                'monthly_income' => '18000',
                'is_literate' => true,
                'tools' => json_encode(['office','cloud','social']),
                'can_commit' => true,
                'willing_overtime' => true,
                'comfortable_clerical' => true,
                'strong_communication' => false,
                'willing_training' => true,
                'other_skills' => 'Photography, Basketball',
            ],
            [
                'student_name' => 'Liza Manalo',
                'course' => 'SOE',
                'year_level' => 'First Year',
                'age' => '19',
                'id_number' => '21-0606-220',
                'address' => '404 Fourth St',
                'email' => 'liza.manalo@example.com',
                'telephone' => '09223334445',
                'picture' => 'liza.jpg',
                'father_name' => 'Roberto Manalo',
                'father_age' => '49',
                'father_occupation' => 'Security Guard',
                'mother_name' => 'Celia Manalo',
                'mother_age' => '47',
                'mother_occupation' => 'Seamstress',
                'monthly_income' => '15000',
                'is_literate' => true,
                'tools' => json_encode(['office','design','video_conf']),
                'can_commit' => true,
                'willing_overtime' => false,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Painting, Reading',
            ],
            [
                'student_name' => 'Mark Tan',
                'course' => 'STE',
                'year_level' => 'Fifth Year',
                'age' => '23',
                'id_number' => '21-0606-221',
                'address' => '505 Fifth Ave',
                'email' => 'mark.tan@example.com',
                'telephone' => '09334445567',
                'picture' => 'mark.jpg',
                'father_name' => 'Samuel Tan',
                'father_age' => '56',
                'father_occupation' => 'Businessman',
                'mother_name' => 'Grace Tan',
                'mother_age' => '54',
                'mother_occupation' => 'Businesswoman',
                'monthly_income' => '35000',
                'is_literate' => true,
                'tools' => json_encode(['office','cloud','video_conf']),
                'can_commit' => true,
                'willing_overtime' => true,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Swimming, Chess',
            ],
            [
                'student_name' => 'Anna Cruz',
                'course' => 'SOH',
                'year_level' => 'Second Year',
                'age' => '20',
                'id_number' => '21-0606-222',
                'address' => '606 Sixth St',
                'email' => 'anna.cruz@example.com',
                'telephone' => '09445556678',
                'picture' => 'anna.jpg',
                'father_name' => 'Antonio Cruz',
                'father_age' => '53',
                'father_occupation' => 'Farmer',
                'mother_name' => 'Elena Cruz',
                'mother_age' => '51',
                'mother_occupation' => 'Vendor',
                'monthly_income' => '12000',
                'is_literate' => true,
                'tools' => json_encode(['office','social']),
                'can_commit' => true,
                'willing_overtime' => false,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Singing, Volleyball',
            ],
            [
                'student_name' => 'Paolo Reyes',
                'course' => 'SOC',
                'year_level' => 'Third Year',
                'age' => '21',
                'id_number' => '21-0606-223',
                'address' => '707 Seventh St',
                'email' => 'paolo.reyes@example.com',
                'telephone' => '09556667788',
                'picture' => 'paolo.jpg',
                'father_name' => 'Mario Reyes',
                'father_age' => '55',
                'father_occupation' => 'Electrician',
                'mother_name' => 'Rosa Reyes',
                'mother_age' => '53',
                'mother_occupation' => 'Teacher',
                'monthly_income' => '22000',
                'is_literate' => true,
                'tools' => json_encode(['office','cloud']),
                'can_commit' => true,
                'willing_overtime' => true,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Guitar, Coding',
            ],
            [
                'student_name' => 'Jessa Dizon',
                'course' => 'SIHM',
                'year_level' => 'First Year',
                'age' => '19',
                'id_number' => '21-0606-224',
                'address' => '808 Eighth St',
                'email' => 'jessa.dizon@example.com',
                'telephone' => '09667778899',
                'picture' => 'jessa.jpg',
                'father_name' => 'Ramon Dizon',
                'father_age' => '48',
                'father_occupation' => 'Chef',
                'mother_name' => 'Lorna Dizon',
                'mother_age' => '46',
                'mother_occupation' => 'Waitress',
                'monthly_income' => '17000',
                'is_literate' => true,
                'tools' => json_encode(['office','design']),
                'can_commit' => true,
                'willing_overtime' => false,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Baking, Drawing',
            ],
            [
                'student_name' => 'Kevin Uy',
                'course' => 'SOHS',
                'year_level' => 'Fourth Year',
                'age' => '22',
                'id_number' => '21-0606-225',
                'address' => '909 Ninth St',
                'email' => 'kevin.uy@example.com',
                'telephone' => '09778889900',
                'picture' => 'kevin.jpg',
                'father_name' => 'Albert Uy',
                'father_age' => '52',
                'father_occupation' => 'Accountant',
                'mother_name' => 'Susan Uy',
                'mother_age' => '50',
                'mother_occupation' => 'Accountant',
                'monthly_income' => '30000',
                'is_literate' => true,
                'tools' => json_encode(['office','video_conf','cloud']),
                'can_commit' => true,
                'willing_overtime' => true,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Photography, Excel',
            ],
            [
                'student_name' => 'Mia Torres',
                'course' => 'SOE',
                'year_level' => 'Second Year',
                'age' => '20',
                'id_number' => '21-0606-226',
                'address' => '1010 Tenth St',
                'email' => 'mia.torres@example.com',
                'telephone' => '09889990011',
                'picture' => 'mia.jpg',
                'father_name' => 'Victor Torres',
                'father_age' => '50',
                'father_occupation' => 'Engineer',
                'mother_name' => 'Carmen Torres',
                'mother_age' => '48',
                'mother_occupation' => 'Doctor',
                'monthly_income' => '40000',
                'is_literate' => true,
                'tools' => json_encode(['office','design','cloud']),
                'can_commit' => true,
                'willing_overtime' => false,
                'comfortable_clerical' => true,
                'strong_communication' => true,
                'willing_training' => true,
                'other_skills' => 'Singing, Programming',
            ],
        ];

        foreach ($applications as $application) {
            Application::create($application);
        }
    }
}
