<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'student_name' => 'Juan Dela Cruz',
                'course' => 'SITE',
                'year_level' => 'Third Year',
                'id_number' => '21-0606-217',
                'age' => 21,
                'address' => '123 Main St',
                'email' => 'juan.delacruz@example.com',
                'telephone' => '09123456789',
                'picture' => 'juan.jpg',
                'designated_office' => 'Registrar',
                'father_name' => 'Pedro Dela Cruz',
                'father_age' => 50,
                'father_occupation' => 'Driver',
                'mother_name' => 'Maria Dela Cruz',
                'mother_age' => 48,
                'mother_occupation' => 'Vendor',
                'monthly_income' => '20000',
                'is_literate' => 1,
                'tools' => json_encode(['office','design']),
                'can_commit' => 1,
                'willing_overtime' => 1,
                'comfortable_clerical' => 1,
                'strong_communication' => 1,
                'willing_training' => 1,
                'other_skills' => 'Singing, Drawing',
            ],
            [
                'student_name' => 'Maria Santos',
                'course' => 'SBA',
                'year_level' => 'Second Year',
                'id_number' => '21-0606-218',
                'age' => 20,
                'address' => '456 Second St',
                'email' => 'maria.santos@example.com',
                'telephone' => '09987654321',
                'picture' => 'maria.jpg',
                'designated_office' => 'Accounting',
                'father_name' => 'Jose Santos',
                'father_age' => 52,
                'father_occupation' => 'Teacher',
                'mother_name' => 'Ana Santos',
                'mother_age' => 50,
                'mother_occupation' => 'Nurse',
                'monthly_income' => '25000',
                'is_literate' => 1,
                'tools' => json_encode(['office','video_conf']),
                'can_commit' => 1,
                'willing_overtime' => 0,
                'comfortable_clerical' => 1,
                'strong_communication' => 1,
                'willing_training' => 1,
                'other_skills' => 'Dancing, Cooking',
            ],
            [
                'student_name' => 'Carlos Rivera',
                'course' => 'SOHS',
                'year_level' => 'Fourth Year',
                'id_number' => '21-0606-219',
                'age' => 22,
                'address' => '789 Third Ave',
                'email' => 'carlos.rivera@example.com',
                'telephone' => '09121234567',
                'picture' => 'carlos.jpg',
                'designated_office' => 'Library',
                'father_name' => 'Miguel Rivera',
                'father_age' => 54,
                'father_occupation' => 'Mechanic',
                'mother_name' => 'Luisa Rivera',
                'mother_age' => 51,
                'mother_occupation' => 'Housewife',
                'monthly_income' => '18000',
                'is_literate' => 1,
                'tools' => json_encode(['office','cloud','social']),
                'can_commit' => 1,
                'willing_overtime' => 1,
                'comfortable_clerical' => 1,
                'strong_communication' => 0,
                'willing_training' => 1,
                'other_skills' => 'Photography, Basketball',
            ],
            [
                'student_name' => 'Liza Manalo',
                'course' => 'SOE',
                'year_level' => 'First Year',
                'id_number' => '21-0606-220',
                'age' => 19,
                'address' => '321 Fourth St',
                'email' => 'liza.manalo@example.com',
                'telephone' => '09223334444',
                'picture' => 'liza.jpg',
                'designated_office' => 'Guidance',
                'father_name' => 'Roberto Manalo',
                'father_age' => 49,
                'father_occupation' => 'Security Guard',
                'mother_name' => 'Celia Manalo',
                'mother_age' => 47,
                'mother_occupation' => 'Seamstress',
                'monthly_income' => '15000',
                'is_literate' => 1,
                'tools' => json_encode(['office','design','video_conf']),
                'can_commit' => 1,
                'willing_overtime' => 0,
                'comfortable_clerical' => 1,
                'strong_communication' => 1,
                'willing_training' => 1,
                'other_skills' => 'Painting, Reading',
            ],
            [
                'student_name' => 'Mark Tan',
                'course' => 'STE',
                'year_level' => 'Fifth Year',
                'id_number' => '20-2100-005',
                'age' => 23,
                'address' => '654 Fifth Ave',
                'email' => 'mark.tan@example.com',
                'telephone' => '09334445566',
                'picture' => 'mark.jpg',
                'designated_office' => 'Clinic',
                'father_name' => 'Samuel Tan',
                'father_age' => 56,
                'father_occupation' => 'Businessman',
                'mother_name' => 'Grace Tan',
                'mother_age' => 54,
                'mother_occupation' => 'Businesswoman',
                'monthly_income' => '35000',
                'is_literate' => 1,
                'tools' => json_encode(['office','cloud','video_conf']),
                'can_commit' => 1,
                'willing_overtime' => 1,
                'comfortable_clerical' => 1,
                'strong_communication' => 1,
                'willing_training' => 1,
                'other_skills' => 'Swimming, Chess',
            ],
            [
                'student_name' => 'Anna Cruz',
                'course' => 'SOH',
                'year_level' => 'Second Year',
                'id_number' => '20-2100-006',
                'age' => 20,
                'address' => '987 Sixth St',
                'email' => 'anna.cruz@example.com',
                'telephone' => '09445556677',
                'picture' => 'anna.jpg',
                'designated_office' => 'Registrar',
                'father_name' => 'Antonio Cruz',
                'father_age' => 53,
                'father_occupation' => 'Farmer',
                'mother_name' => 'Elena Cruz',
                'mother_age' => 51,
                'mother_occupation' => 'Vendor',
                'monthly_income' => '12000',
                'is_literate' => 1,
                'tools' => json_encode(['office','social']),
                'can_commit' => 1,
                'willing_overtime' => 0,
                'comfortable_clerical' => 1,
                'strong_communication' => 1,
                'willing_training' => 1,
                'other_skills' => 'Singing, Volleyball',
            ],
        ];

        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
